---
- name: cretate web user
  user:
    name: stsweb
    comment: "v1 version"
    shell: /bin/bash
    password: "{{ npass| password_hash('sha512') }}"
    update_password: always
    state: present
  no_log: true

- name: record  pass
  shell: |
    echo "{{inventory_hostname}},stsweb,{{ npass }}" >> {{ playbook_dir }}/out.csv
  delegate_to: 127.0.0.1